# The config of the 2s10x10-3p-3f scenario with the VectorObserver set as default
task_name: 2s-10x10-3p-3f

task_config:
  grid_size: 10
  fov: 2
  num_agents: 3
  num_food: 3
  max_agent_level: 2
  force_coop: False
