name: Tests and Linters 🧪

on: [ push, pull_request ]

jobs:
  tests-and-linters:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    timeout-minutes: 10

    strategy:
      matrix:
        python-version: ["3.9"]
        os: [ubuntu-latest]

    steps:
      - name: Checkout mava
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
            python-version: "${{ matrix.python-version }}"
      - name: Install python dependencies 🔧
        run: pip install .[dev]
      - name: Run linters 🖌️
        run: pre-commit run --all-files --verbose
